### ISSUE TITLE
Skip works when specified in feeds, not at top of file

### ISSUE THREAD

**Issue by sfinlon** [csirtgadgets/csirtg-smrt-py#101]
Skip works here:
```
parser: csv
defaults:
  provider: test
  altid_tlp: amber
  tlp: amber
  confidence: 9

feeds:
  botnet:
    parser: csv
    skip: android_stels|auto|darkmailer|feodo|festi|maazben|netsky|rodecap|sendsafe|smtpauth|stealrat|unknown|worm_boinberg|zapchast
    remote: '/tmp/testskip.txt'
    defaults:
      values:
        - indicator
        - asn
        - cc
        - lastseen
        - description
        - rdata
        - null
        - null
        - portlist
        - protocol
      tags:
        - botnet
```
Here is a sample output with skip working, test file is attached at the bottom:
```
$ csirtg-smrt -r rules/default/testskip.yml
2016-12-21 10:58:11,960 - INFO - root[276] - loglevel is: INFO
2016-12-21 10:58:11,960 - INFO - root[316] - starting...
+-------+----------+------------+-------+-----------------+-------+----+--------+----------+------------+-------------+--------+------------------------+----------+
|  tlp  | lasttime | reporttime | itype |    indicator    | count | cc |  asn   | asn_desc | confidence | description |  tags  |         rdata          | provider |
+-------+----------+------------+-------+-----------------+-------+----+--------+----------+------------+-------------+--------+------------------------+----------+
| amber |          |            |  ipv4 |  192.168.125.29 |       | CA | AS0000 |          |     9      |   gamarue   | botnet |      restless.su       | test     |
| amber |          |            |  ipv4 |   192.168.0.7   |       | US | AS0000 |          |     9      |     gozi    | botnet |      portoyea.at       | test     |
| amber |          |            |  ipv4 | 192.168.192.210 |       | US | AS0000 |          |     9      |  zeroaccess | botnet |                        | test     |
| amber |          |            |  ipv4 | 192.168.240.134 |       | US | AS0000 |          |     9      |   citadel   | botnet |      sonic4us.ru       | test     |
| amber |          |            |  ipv4 | 192.168.128.105 |       | US | AS0000 |          |     9      |    tinba    | botnet | forumforneverwind2.com | test     |
| amber |          |            |  ipv4 | 192.168.202.126 |       | US | AS0000 |          |     9      |  conficker  | botnet |     192.42.116.41      | test     |
+-------+----------+------------+-------+-----------------+-------+----+--------+----------+------------+-------------+--------+------------------------+----------+
2016-12-21 10:58:11,998 - INFO - root[362] - completed
```

Here is a sample output with skip not working, test file is attached at the bottom:
```
parser: csv
skip: android_stels|auto|darkmailer|feodo|festi|maazben|netsky|rodecap|sendsafe|smtpauth|stealrat|unknown|worm_boinberg|zapchast
defaults:
  provider: test
  altid_tlp: amber
  tlp: amber
  confidence: 9

feeds:
  botnet:
    parser: csv
    remote: '/tmp/testskip.txt'
    defaults:
      values:
        - indicator
        - asn
        - cc
        - lastseen
        - description
        - rdata
        - null
        - null
        - portlist
        - protocol
      tags:
        - botnet
```
This is output with skip at top of file:
```
$ csirtg-smrt -r rules/default/testskip.yml
2016-12-21 10:57:33,780 - INFO - root[276] - loglevel is: INFO
2016-12-21 10:57:33,780 - INFO - root[316] - starting...
+-------+----------+------------+-------+-----------------+-------+----+--------+----------+------------+---------------+--------+------------------------+----------+
|  tlp  | lasttime | reporttime | itype |    indicator    | count | cc |  asn   | asn_desc | confidence |  description  |  tags  |         rdata          | provider |
+-------+----------+------------+-------+-----------------+-------+----+--------+----------+------------+---------------+--------+------------------------+----------+
| amber |          |            |  ipv4 |  192.168.203.13 |       | US | AS0000 |          |     9      |    zapchast   | botnet |    uyhgqunqkxnx.pw     | test     |
| amber |          |            |  ipv4 |  192.168.125.29 |       | CA | AS0000 |          |     9      |    gamarue    | botnet |      restless.su       | test     |
| amber |          |            |  ipv4 |  192.168.125.28 |       | CA | AS0000 |          |     9      | worm_boinberg | botnet |      restless.su       | test     |
| amber |          |            |  ipv4 |   192.168.0.7   |       | US | AS0000 |          |     9      |      gozi     | botnet |      portoyea.at       | test     |
| amber |          |            |  ipv4 |  192.168.252.26 |       | US | AS0000 |          |     9      |    stealrat   | botnet |           1            | test     |
| amber |          |            |  ipv4 | 192.168.192.210 |       | US | AS0000 |          |     9      |   zeroaccess  | botnet |                        | test     |
| amber |          |            |  ipv4 | 192.168.240.134 |       | US | AS0000 |          |     9      |    citadel    | botnet |      sonic4us.ru       | test     |
| amber |          |            |  ipv4 | 192.168.240.133 |       | US | AS0000 |          |     9      |    smtpauth   | botnet |      sonic4us.ru       | test     |
| amber |          |            |  ipv4 | 192.168.240.132 |       | US | AS0000 |          |     9      |    rodecap    | botnet |      sonic4us.ru       | test     |
| amber |          |            |  ipv4 | 192.168.240.131 |       | US | AS0000 |          |     9      |     netsky    | botnet |      sonic4us.ru       | test     |
| amber |          |            |  ipv4 | 192.168.128.105 |       | US | AS0000 |          |     9      |     tinba     | botnet | forumforneverwind2.com | test     |
| amber |          |            |  ipv4 |  192.168.39.49  |       | US | AS0000 |          |     9      |    maazben    | botnet |           -            | test     |
| amber |          |            |  ipv4 |  192.168.191.97 |       | US | AS0000 |          |     9      |  unknown3013  | botnet |                        | test     |
| amber |          |            |  ipv4 | 192.168.135.115 |       | US | AS0000 |          |     9      |     festi     | botnet |           2            | test     |
| amber |          |            |  ipv4 |  192.168.245.5  |       | US | AS0000 |          |     9      |     feodo     | botnet |                        | test     |
| amber |          |            |  ipv4 | 192.168.146.125 |       | US | AS0000 |          |     9      |   darkmailer  | botnet |    babanuraspear.ru    | test     |
| amber |          |            |  ipv4 | 192.168.207.170 |       | US | AS0000 |          |     9      |    sendsafe   | botnet |  2016/12/14-08:08:03   | test     |
| amber |          |            |  ipv4 | 192.168.202.126 |       | US | AS0000 |          |     9      |   conficker   | botnet |     192.42.116.41      | test     |
| amber |          |            |  ipv4 | 192.168.151.122 |       | US | AS0000 |          |     9      |      auto     | botnet |           -            | test     |
| amber |          |            |  ipv4 |  192.168.9.252  |       | US | AS0000 |          |     9      | android_stels | botnet |           1            | test     |
+-------+----------+------------+-------+-----------------+-------+----+--------+----------+------------+---------------+--------+------------------------+----------+
2016-12-21 10:57:33,831 - INFO - root[362] - completed
```

Here is my test file:
```
192.168.9.252,AS0000,US,1481801117,android_stels,1,38.102.150.27,80,50809,tcp
192.168.151.122,AS0000,US,1481761135,auto,-,,2323,7894,tcp
192.168.202.126,AS0000,US,1481785068,conficker,192.42.116.41,192.42.116.41,80,44087,tcp
192.168.207.170,AS0000,US,1481792047,sendsafe,2016/12/14-08:08:03,,25,,tcp
192.168.146.125,AS0000,US,1481835257,darkmailer,babanuraspear.ru,192.42.116.41,80,47908,tcp
192.168.245.5,AS0000,US,1481772139,feodo,,,25,,tcp
192.168.135.115,AS0000,US,1481763799,festi,2,38.229.178.226,80,52063,tcp
192.168.191.97,AS0000,US,1481799343,unknown3013,,,25,,tcp
192.168.39.49,AS0000,US,1481759670,maazben,-,,23,65061,tcp
192.168.128.105,AS0000,US,1481806658,tinba,forumforneverwind2.com,87.106.190.153,80,46084,tcp
192.168.240.131,AS0000,US,1481805028,netsky,sonic4us.ru,192.42.116.41,80,1079,tcp
192.168.240.132,AS0000,US,1481804787,rodecap,sonic4us.ru,192.42.116.41,80,1079,tcp
192.168.240.133,AS0000,US,1481757313,smtpauth,sonic4us.ru,192.42.116.41,80,1071,tcp
192.168.240.134,AS0000,US,1481805469,citadel,sonic4us.ru,192.42.116.41,80,1071,tcp
192.168.192.210,AS0000,US,1481808083,zeroaccess,,68.14.148.164,16470,50653,udp
192.168.252.26,AS0000,US,1481832674,stealrat,1,104.244.14.252,80,22680,tcp
192.168.0.7,AS0000,US,1481764288,gozi,portoyea.at,192.42.116.41,80,61429,tcp
192.168.125.28,AS0000,CA,1481837377,worm_boinberg,restless.su,192.42.116.41,80,37539,tcp
192.168.125.29,AS0000,CA,1481765745,gamarue,restless.su,192.42.116.41,80,49165,tcp
192.168.203.13,AS0000,US,1481779960,zapchast,uyhgqunqkxnx.pw,192.42.116.41,80,53076,tcp
```
