### ISSUE TITLE
problem: values flag doesn't override

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-smrt-py#230]
```
defaults:
  provider: spamhaus.org
  confidence: 9 
  tlp: green
  reference_tlp: white
  tags:
    - hijacked
  reference: http://www.spamhaus.org/sbl/sbl.lasso?query=<reference>
  pattern: '(.+)\s;\s(.+)'
  values:
    - indicator
    - reference

feeds:
  drop:
    remote: http://www.spamhaus.org/drop/drop.txt

  edrop:
    remote: http://www.spamhaus.org/drop/edrop.txt

  dropv6:
    remote: https://www.spamhaus.org/drop/dropv6.txt

  asndrop:
    remote: https://www.spamhaus.org/drop/asndrop.txt
    pattern: '^(\S+) ; ([\S+]{2}) \| ([^\n]+)$'
    #values:
    #  - indicator
    #  - cc
    #  - asn_desc

```
